import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import profilesPic from "../../public/images/profile/developer.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bao's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilesPic}
                alt="DA"
                className="w-full h-auto"
              ></Image>
            </div>
            <div className="w-1/2">
              <AnimatedText
                text="Turning data into insights"
                className="!text-6xl text-left"
              ></AnimatedText>
              <p className="my-4 text-base font-medium">
                As a youthful junior student and a passion data analyst, I'm
                interested in working with data, willing to equip new knowledge,
                upgrade myself to align perfectly with the demands of the job. I
                am currently available and ready to contribute as a full-time
                intern, offering my dedicated commitment to actively engage and
                play a part to the organization's goals.
              </p>
              <Link href="/">My Resume</Link>
              <Link href="baotran310702@gmail.com">Email Contact</Link>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
